# Test properties for Docker environment
api.ribbon.listOfServers=backend:8080
api.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList

# Push messaging config
zuul.push.http.port=7008
