# Test properties
eureka.shouldFetchRegistry=false
eureka.registration.enabled=false

public.ribbon.listOfServers=127.0.0.1:8080
public.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList

admin.ribbon.listOfServers=127.0.0.1:8081
admin.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
